// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarkAid.Api.Data;

#nullable disable

namespace StarkAid.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260105012831_AddDominioAudioResolver")]
    partial class AddDominioAudioResolver
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StarkAid.Api.Entities.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AgendadoPara")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Comando")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DispositivoEspId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EwelinkDeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Executado")
                        .HasColumnType("bit");

                    b.Property<string>("Recorrencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoAgendamento")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("DispositivoEspId");

                    b.HasIndex("UserId");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.AiInteractionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AprendizadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AprendizadoTipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ChamouIaExterna")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("EconomiaUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LatenciaMs")
                        .HasColumnType("int");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("SimilarityScore")
                        .HasColumnType("float");

                    b.Property<string>("TextoNormalizado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextoOriginal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokensEstimadosEvitados")
                        .HasColumnType("int");

                    b.Property<string>("UserHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AiInteractionEvents");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.Aprendizado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("int");

                    b.Property<string>("Contexto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("EmQuarentena")
                        .HasColumnType("bit");

                    b.Property<int>("HitCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("QuarentenaDesde")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Resposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UltimaRessurreicaoAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VariantesDistintasUsadas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Tipo")
                        .HasFilter("[Tipo] = 'Global'");

                    b.HasIndex("UserId", "Tipo");

                    b.ToTable("Aprendizados");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.AprendizadoResposta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AprendizadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsoCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AprendizadoId");

                    b.ToTable("AprendizadoRespostas");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.Assinatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CanceladaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ExpiraEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("IniciadaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("PagamentoConfirmadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StripePriceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoPlano")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Assinaturas");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.ComandoSocial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comando")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespostasAleatorias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ComandosSociais");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.ConfiguracaoSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DominioAudioResolver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DominioCloudflare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DominioNlp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesSistema");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.ConfiguracaoStarkNlp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("StarkNlpUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesStarkNlp");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Comando")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MqttTopic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.Disparo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Confirmado")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ConfirmadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DisparadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DispositivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoId");

                    b.HasIndex("UserId");

                    b.ToTable("Disparos");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.DispositivoDisparo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MqttTopic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("StatusTopic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DispositivosDisparo");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.DispositivoEsp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComandToEsp")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Comando")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTimeOffset?>("LastPingAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("LigadoDesligado")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Porta")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DispositivosEsp");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.ErrorCodeDescription", b =>
                {
                    b.Property<string>("CodigoDeErro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CamposRelevantes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contexto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Solucoes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoDeErro");

                    b.ToTable("ErrorCodeDescriptions");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.ErrorLogApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcaoErro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoDeErro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DataErro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ErroCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraErro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UltimaResposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UltimoComando")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UltimoDispositivoAcionado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ErrorLogsApp");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.ErrorLogSoft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcaoErro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoDeErro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DataErro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ErroCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraErro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UltimaResposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UltimoComando")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UltimoDispositivoAcionado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ErrorLogsSoft");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.EwelinkAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("AccessTokenExpiry")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("RefreshTokenExpiry")
                        .HasColumnType("bigint");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EwelinkAccounts");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.EwelinkDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FamilyId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Online")
                        .HasColumnType("bit");

                    b.Property<string>("Params")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Uiid")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EwelinkDevices");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.FirebaseToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FirebaseTokens");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.GcExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DataExecucao")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("DuracaoMs")
                        .HasColumnType("bigint");

                    b.Property<int>("ItensEmQuarentena")
                        .HasColumnType("int");

                    b.Property<int>("ItensInativados")
                        .HasColumnType("int");

                    b.Property<int>("ItensRessuscitados")
                        .HasColumnType("int");

                    b.Property<string>("LogDetalhado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GcExecutionLogs");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.IaHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TextoIa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("IaHistoricos");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.License", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaxMachines")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PaymentConfirmedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StripeSessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.LicenseActivation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ActivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MachineName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId");

                    b.ToTable("LicenseActivations");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.LogFalhaSoft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComandoTentado")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DispositivoNome")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ErroDetalhado")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TipoFalha")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LogsFalhasSoft", (string)null);
                });

            modelBuilder.Entity("StarkAid.Api.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Lida")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LidaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenciaId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("StarkAid.Api.Entities.PagamentoAvulso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("PagamentoConfirmadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PagamentosAvulsos");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Expiration")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.Piada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Piadas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativa = true,
                            Categoria = "Tecnologia",
                            Texto = "Por que o computador foi ao médico? Porque estava com vírus."
                        },
                        new
                        {
                            Id = 2,
                            Ativa = true,
                            Categoria = "Geral",
                            Texto = "O que o zero disse para o oito? Que cinto bonito!"
                        },
                        new
                        {
                            Id = 3,
                            Ativa = true,
                            Categoria = "Escola",
                            Texto = "Por que o livro de matemática se suicidou? Porque tinha muitos problemas."
                        },
                        new
                        {
                            Id = 4,
                            Ativa = true,
                            Categoria = "Geral",
                            Texto = "Qual é o cúmulo da força? Dobrar a esquina."
                        },
                        new
                        {
                            Id = 5,
                            Ativa = true,
                            Categoria = "Tecnologia",
                            Texto = "O que uma impressora disse para a outra? Essa folha é sua ou é impressão minha?"
                        },
                        new
                        {
                            Id = 6,
                            Ativa = true,
                            Categoria = "Natureza",
                            Texto = "Por que a plantinha não foi ao médico? Porque só tinha médico de plantão."
                        },
                        new
                        {
                            Id = 7,
                            Ativa = true,
                            Categoria = "Animais",
                            Texto = "O que o pato disse para a pata? Vem Quá!"
                        },
                        new
                        {
                            Id = 8,
                            Ativa = true,
                            Categoria = "Geral",
                            Texto = "Qual o pé que é mais rápido? O pé-ligeiro."
                        },
                        new
                        {
                            Id = 9,
                            Ativa = true,
                            Categoria = "Natureza",
                            Texto = "Por que o pinheiro não se perde na floresta? Porque ele tem uma pinha."
                        },
                        new
                        {
                            Id = 10,
                            Ativa = true,
                            Categoria = "Comida",
                            Texto = "O que o tomate foi fazer no banco? Tirar extrato."
                        },
                        new
                        {
                            Id = 11,
                            Ativa = true,
                            Categoria = "Tecnologia",
                            Texto = "Qual é a tecla preferida do astronauta? A barra de espaço."
                        },
                        new
                        {
                            Id = 12,
                            Ativa = true,
                            Categoria = "Animais",
                            Texto = "Por que o jacaré tirou o filho da escola? Porque ele réptil de ano."
                        },
                        new
                        {
                            Id = 13,
                            Ativa = true,
                            Categoria = "Comida",
                            Texto = "Qual é o rei dos queijos? O Requeijão."
                        },
                        new
                        {
                            Id = 14,
                            Ativa = true,
                            Categoria = "Geral",
                            Texto = "O que é um ponto verde na antártida? Um ping-green."
                        },
                        new
                        {
                            Id = 15,
                            Ativa = true,
                            Categoria = "Profissões",
                            Texto = "Por que o bombeiro não gosta de andar? Porque ele socorre."
                        },
                        new
                        {
                            Id = 16,
                            Ativa = true,
                            Categoria = "Animais",
                            Texto = "Qual é o animal que não vale mais nada? O javali."
                        },
                        new
                        {
                            Id = 17,
                            Ativa = true,
                            Categoria = "Geral",
                            Texto = "O que o pagodeiro foi fazer na igreja? Cantar pá god."
                        },
                        new
                        {
                            Id = 18,
                            Ativa = true,
                            Categoria = "Geral",
                            Texto = "Por que a velhinha não usa relógio? Porque ela é sem hora."
                        },
                        new
                        {
                            Id = 19,
                            Ativa = true,
                            Categoria = "Herois",
                            Texto = "Como o Batman faz para entrar na Bat-caverna? Ele bat-palma."
                        },
                        new
                        {
                            Id = 20,
                            Ativa = true,
                            Categoria = "Ciencia",
                            Texto = "Qual o doce preferido do átomo? Pé-de-moleculas."
                        },
                        new
                        {
                            Id = 21,
                            Ativa = true,
                            Categoria = "Espaço",
                            Texto = "O que a Lua disse ao Sol? Nossa, você é tão grande e não te deixam sair à noite!"
                        },
                        new
                        {
                            Id = 22,
                            Ativa = true,
                            Categoria = "Ciencia",
                            Texto = "Por que as estrelas não fazem miau? Porque Astronomia."
                        },
                        new
                        {
                            Id = 23,
                            Ativa = true,
                            Categoria = "Comida",
                            Texto = "O que a banana suicida falou? Macacos me mordam!"
                        },
                        new
                        {
                            Id = 24,
                            Ativa = true,
                            Categoria = "Geografia",
                            Texto = "Qual o estado que quer ser carro? Sergipe."
                        },
                        new
                        {
                            Id = 25,
                            Ativa = true,
                            Categoria = "Charada",
                            Texto = "O que é, o que é: cai em pé e corre deitado? A chuva."
                        },
                        new
                        {
                            Id = 26,
                            Ativa = true,
                            Categoria = "Geral",
                            Texto = "Em qual cidade o Thor mora? Valhalla? Não, Pousada."
                        },
                        new
                        {
                            Id = 27,
                            Ativa = true,
                            Categoria = "Ciencia",
                            Texto = "Por que o elétron não foi à festa? Porque precisa ser positivo."
                        },
                        new
                        {
                            Id = 28,
                            Ativa = true,
                            Categoria = "Animais",
                            Texto = "O que o advogado do frango foi fazer? Foi soltar a franga."
                        },
                        new
                        {
                            Id = 29,
                            Ativa = true,
                            Categoria = "Animais",
                            Texto = "Qual a diferença entre o gato e a coca-cola? O gato faz miau e a coca-cola faz tshhh."
                        },
                        new
                        {
                            Id = 30,
                            Ativa = true,
                            Categoria = "Ferramentas",
                            Texto = "O que o martelo foi fazer no culto? Pregador."
                        });
                });

            modelBuilder.Entity("StarkAid.Api.Entities.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredientes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Receitas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Doces",
                            Ingredientes = "3 cenouras, 4 ovos, 1 xícara de óleo, 2 xícaras de açúcar, 2 xícaras de farinha, 1 colher de fermento.",
                            Nome = "Bolo de Cenoura"
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Salgados",
                            Ingredientes = "2 ovos, sal a gosto, queijo, presunto, orégano.",
                            Nome = "Omelete Simples"
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Acompanhamentos",
                            Ingredientes = "1 xícara de arroz, 2 xícaras de água, alho, sal, óleo.",
                            Nome = "Arroz Branco"
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "Doces",
                            Ingredientes = "1 lata de leite condensado, 4 colheres de chocolate em pó, 1 colher de manteiga, granulado.",
                            Nome = "Brigadeiro"
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "Bebidas",
                            Ingredientes = "3 limões, 1 litro de água, açúcar ou adoçante a gosto, gelo.",
                            Nome = "Suco de Limão"
                        });
                });

            modelBuilder.Entity("StarkAid.Api.Entities.ReceitaPasso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("ReceitaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceitaId");

                    b.ToTable("ReceitaPassos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Descasque e corte as cenouras em rodelas.",
                            Ordem = 1,
                            ReceitaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "No liquidificador, bata as cenouras, os ovos e o óleo.",
                            Ordem = 2,
                            ReceitaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Em uma tigela, misture o açúcar, a farinha e o fermento.",
                            Ordem = 3,
                            ReceitaId = 1
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Despeje a mistura do liquidificador na tigela e mexa bem.",
                            Ordem = 4,
                            ReceitaId = 1
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Unte uma forma e despeje a massa.",
                            Ordem = 5,
                            ReceitaId = 1
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Asse em forno pré-aquecido a 180 graus por 40 minutos.",
                            Ordem = 6,
                            ReceitaId = 1
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Quebre os ovos em um prato fundo.",
                            Ordem = 1,
                            ReceitaId = 2
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Bata os ovos ligeiramente com um garfo.",
                            Ordem = 2,
                            ReceitaId = 2
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Tempere com sal e orégano.",
                            Ordem = 3,
                            ReceitaId = 2
                        },
                        new
                        {
                            Id = 10,
                            Descricao = "Aqueça uma frigideira com um pouco de óleo.",
                            Ordem = 4,
                            ReceitaId = 2
                        },
                        new
                        {
                            Id = 11,
                            Descricao = "Despeje os ovos e adicione o queijo e presunto.",
                            Ordem = 5,
                            ReceitaId = 2
                        },
                        new
                        {
                            Id = 12,
                            Descricao = "Dobre ao meio e deixe dourar dos dois lados.",
                            Ordem = 6,
                            ReceitaId = 2
                        },
                        new
                        {
                            Id = 13,
                            Descricao = "Lave o arroz se desejar.",
                            Ordem = 1,
                            ReceitaId = 3
                        },
                        new
                        {
                            Id = 14,
                            Descricao = "Aqueça o óleo e refogue o alho picado.",
                            Ordem = 2,
                            ReceitaId = 3
                        },
                        new
                        {
                            Id = 15,
                            Descricao = "Adicione o arroz e refogue por um minuto.",
                            Ordem = 3,
                            ReceitaId = 3
                        },
                        new
                        {
                            Id = 16,
                            Descricao = "Adicione a água fervente e o sal.",
                            Ordem = 4,
                            ReceitaId = 3
                        },
                        new
                        {
                            Id = 17,
                            Descricao = "Cozinhe em fogo baixo com a panela semi-tampada.",
                            Ordem = 5,
                            ReceitaId = 3
                        },
                        new
                        {
                            Id = 18,
                            Descricao = "Quando a água secar, desligue e deixe descansar.",
                            Ordem = 6,
                            ReceitaId = 3
                        },
                        new
                        {
                            Id = 19,
                            Descricao = "Em uma panela, coloque o leite condensado.",
                            Ordem = 1,
                            ReceitaId = 4
                        },
                        new
                        {
                            Id = 20,
                            Descricao = "Adicione o chocolate em pó e a manteiga.",
                            Ordem = 2,
                            ReceitaId = 4
                        },
                        new
                        {
                            Id = 21,
                            Descricao = "Leve ao fogo baixo, mexendo sempre.",
                            Ordem = 3,
                            ReceitaId = 4
                        },
                        new
                        {
                            Id = 22,
                            Descricao = "Mexa até desgrudar do fundo da panela.",
                            Ordem = 4,
                            ReceitaId = 4
                        },
                        new
                        {
                            Id = 23,
                            Descricao = "Despeje em um prato untado e deixe esfriar.",
                            Ordem = 5,
                            ReceitaId = 4
                        },
                        new
                        {
                            Id = 24,
                            Descricao = "Enrole as bolinhas e passe no granulado.",
                            Ordem = 6,
                            ReceitaId = 4
                        },
                        new
                        {
                            Id = 25,
                            Descricao = "Lave bem os limões.",
                            Ordem = 1,
                            ReceitaId = 5
                        },
                        new
                        {
                            Id = 26,
                            Descricao = "Corte os limões ao meio.",
                            Ordem = 2,
                            ReceitaId = 5
                        },
                        new
                        {
                            Id = 27,
                            Descricao = "Esprema o suco dos limões em uma jarra.",
                            Ordem = 3,
                            ReceitaId = 5
                        },
                        new
                        {
                            Id = 28,
                            Descricao = "Adicione a água e misture.",
                            Ordem = 4,
                            ReceitaId = 5
                        },
                        new
                        {
                            Id = 29,
                            Descricao = "Adoce a gosto e mexa bem até dissolver.",
                            Ordem = 5,
                            ReceitaId = 5
                        },
                        new
                        {
                            Id = 30,
                            Descricao = "Adicione gelo e sirva imediatamente.",
                            Ordem = 6,
                            ReceitaId = 5
                        });
                });

            modelBuilder.Entity("StarkAid.Api.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Expiration")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.ResolvendoSuporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("ResolvidoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ResolvendoSuportes", (string)null);
                });

            modelBuilder.Entity("StarkAid.Api.Entities.StarkCoinPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PackageType")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StarkCoinsAmount")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("StarkCoinPurchases");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.SuporteAcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Resposta")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SuporteAcoes", (string)null);
                });

            modelBuilder.Entity("StarkAid.Api.Entities.SuporteAprendizado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContadorSucesso")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Problema")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Solucoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SuporteAprendizados", (string)null);
                });

            modelBuilder.Entity("StarkAid.Api.Entities.SuporteConversa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ChatConcluido")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ConcluidoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ContadorMensagens")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("LimiteAtingido")
                        .HasColumnType("bit");

                    b.Property<string>("Mensagens")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProblemaInicial")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("bit");

                    b.Property<bool>("TransferidoParaHumano")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SuporteConversas", (string)null);
                });

            modelBuilder.Entity("StarkAid.Api.Entities.SuportePerguntaFrequente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Pergunta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("RequerAcao")
                        .HasColumnType("bit");

                    b.Property<string>("Resposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuporteToApp")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SuporteToSoft")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("SuportePerguntasFrequentes", (string)null);
                });

            modelBuilder.Entity("StarkAid.Api.Entities.Telemetria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Telemetrias");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Estado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("MinutosReconhecidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("PreapprovalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RemovalAds")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SpotifyAccessToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SpotifyRefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("SpotifyTokenExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("StarkCoins")
                        .HasColumnType("int");

                    b.Property<int>("TokensConsumidosSemana")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UltimoPagamentoConfirmadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WhatsAppSessionData")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.UserActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UltimaRespostaIA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UltimaRespostaSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UltimoComandoEsp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UltimoComandoEwelink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UltimoComandoIA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UltimoComandoSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UltimoComandoStarkSwitch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserActivities");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.UserConversaContext", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContextoAtual")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("UserId");

                    b.ToTable("UserConversaContexts");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.UserFunState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IniciouPassoAPasso")
                        .HasColumnType("bit");

                    b.Property<int>("PassoAtual")
                        .HasColumnType("int");

                    b.Property<string>("PiadasContadasIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReceitaAtualId")
                        .HasColumnType("int");

                    b.Property<string>("ReceitasVistasIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserFunStates");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.WebhookLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataRecebida")
                        .HasColumnType("datetime2");

                    b.Property<string>("JsonDetalhado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WebhookLogs");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.YouTubeMusicCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("HitCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsLive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedQuery")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedQuery")
                        .IsUnique();

                    b.ToTable("YouTubeMusicCaches");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.Agendamento", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StarkAid.Api.Entities.DispositivoEsp", "DispositivoEsp")
                        .WithMany()
                        .HasForeignKey("DispositivoEspId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany("Agendamentos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("DispositivoEsp");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.Aprendizado", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("StarkAid.Api.Entities.AprendizadoResposta", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.Aprendizado", "Aprendizado")
                        .WithMany("Respostas")
                        .HasForeignKey("AprendizadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aprendizado");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.Assinatura", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany("Assinaturas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.ComandoSocial", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany("ComandosSociais")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.Device", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.Disparo", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.DispositivoDisparo", "Dispositivo")
                        .WithMany("Disparos")
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany("Disparos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dispositivo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.DispositivoDisparo", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany("DispositivosDisparo")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.DispositivoEsp", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.ErrorLogApp", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.ErrorLogSoft", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.EwelinkAccount", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.EwelinkDevice", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.FirebaseToken", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany("FirebaseTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.IaHistorico", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.License", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.LicenseActivation", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.License", "License")
                        .WithMany("Activations")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("License");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.LogFalhaSoft", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.PagamentoAvulso", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.ReceitaPasso", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.Receita", "Receita")
                        .WithMany("Passos")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.RefreshToken", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.ResolvendoSuporte", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.StarkCoinPurchase", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.SuporteAcao", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.SuporteConversa", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.Telemetria", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.UserActivity", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.UserFunState", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("StarkAid.Api.Entities.UserFunState", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.UserSession", b =>
                {
                    b.HasOne("StarkAid.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.Aprendizado", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.DispositivoDisparo", b =>
                {
                    b.Navigation("Disparos");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.License", b =>
                {
                    b.Navigation("Activations");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.Receita", b =>
                {
                    b.Navigation("Passos");
                });

            modelBuilder.Entity("StarkAid.Api.Entities.User", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Assinaturas");

                    b.Navigation("ComandosSociais");

                    b.Navigation("Devices");

                    b.Navigation("Disparos");

                    b.Navigation("DispositivosDisparo");

                    b.Navigation("FirebaseTokens");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
